plugins {
	alias(libs.plugins.shadow)
	id 'application'
}

group = project.maven_group
version = rootProject.version

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

application {
	mainClass = 'ai.moeru.airicraft.wrapper.AiricraftCliMain'
	applicationName = 'airicraft'
}

dependencies {
	implementation libs.picocli
	implementation libs.jackson.databind

	testImplementation platform(libs.junit.bom)
	testImplementation libs.junit.jupiter
	testRuntimeOnly libs.junit.platform.launcher
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(CreateStartScripts).configureEach {
	applicationName = 'airicraft'
	doFirst {
		delete outputDir
	}
}

tasks.named('installDist') {
	doFirst {
		delete layout.buildDirectory.dir("install/${application.applicationName}")
	}
}

jar {
	manifest {
		attributes 'Main-Class': application.mainClass.get()
	}

	archiveClassifier = 'thin'
}

shadowJar {
	configurations = [project.configurations.runtimeClasspath]
	archiveClassifier = ''
}

build {
	dependsOn shadowJar
}
